# Generated by Django 2.0 on 2020-12-29 11:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('voting', '0003_auto_20180605_0842'),
    ]

    operations = [
        migrations.CreateModel(
            name='Census',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_id', models.PositiveIntegerField()),
                ('adscripcion', models.CharField(blank=True, max_length=20, null=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('voting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='voting.Voting')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='census',
            unique_together={('voting', 'voter_id')},
        ),
    ]
