# Generated by Django 2.0 on 2021-01-26 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
