# Generated by Django 2.0 on 2020-12-29 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0002_auto_20201229_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='census',
            name='voting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.Voting'),
        ),
    ]
