# Generated by Django 2.0 on 2020-12-26 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_auto_20180605_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='end_date',
            field=models.CharField(max_length=200),
        ),
    ]
