# Generated by Django 2.0 on 2021-01-05 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_auto_20180605_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='customURL',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
