# Generated by Django 2.0 on 2020-12-26 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_auto_20201226_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voting',
            name='end_date',
        ),
    ]
