# Generated by Django 2.0 on 2020-12-29 17:32

from django.db import migrations, models
import voting.models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_voting_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voting',
            old_name='age',
            new_name='max_age',
        ),
        migrations.AddField(
            model_name='voting',
            name='min_age',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[voting.models.validate_age]),
        ),
    ]
