# Generated by Django 2.0 on 2020-12-28 16:57

from django.db import migrations, models
import voting.models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_questionorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='end_date',
            field=models.DateTimeField(validators=[voting.models.validate_end_date]),
        ),
    ]
