# Generated by Django 2.0 on 2021-01-03 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_auto_20210103_0832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voting',
            old_name='question',
            new_name='questions',
        ),
    ]
