# Generated by Django 2.0 on 2021-01-05 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_readonlyvoting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readonlyvoting',
            name='desc',
            field=models.TextField(default='Example', max_length=100),
        ),
    ]
