# Generated by Django 2.0 on 2021-01-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_questionprefer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionprefer',
            name='prefer',
            field=models.NullBooleanField(),
        ),
    ]
