# Generated by Django 2.0 on 2021-01-14 05:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_auto_20210114_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='customURL',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
