# Generated by Django 2.0 on 2021-01-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_auto_20210102_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionprefer',
            name='prefer',
            field=models.TextField(blank=True, choices=[('YES', 'YES')]),
        ),
    ]
