# Generated by Django 2.0 on 2020-12-30 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_questioncandidate_votingcandidate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionoption',
            name='question',
        ),
        migrations.RemoveField(
            model_name='votingcandidate',
            name='auths',
        ),
        migrations.RemoveField(
            model_name='votingcandidate',
            name='candidates',
        ),
        migrations.RemoveField(
            model_name='votingcandidate',
            name='pub_key',
        ),
        migrations.RemoveField(
            model_name='voting',
            name='question',
        ),
        migrations.AddField(
            model_name='voting',
            name='candidates',
            field=models.ManyToManyField(related_name='voting', to='voting.QuestionCandidate'),
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='QuestionOption',
        ),
        migrations.DeleteModel(
            name='VotingCandidate',
        ),
    ]
