# Generated by Django 2.0 on 2020-12-30 09:33

from django.db import migrations, models
import voting.models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_auto_20201229_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='max_age',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[voting.models.validate_age]),
        ),
    ]
