# Generated by Django 2.0 on 2021-01-14 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_auto_20210114_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='customURL',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
