# Generated by Django 2.0 on 2021-01-04 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_auto_20210102_1126'),
        ('voting', '0006_auto_20201230_0933'),
    ]

    operations = [
    ]
