# Generated by Django 2.0 on 2021-01-05 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_voting_end_date'),
        ('voting', '0005_auto_20201228_1657'),
    ]

    operations = [
    ]
