# Generated by Django 2.0 on 2020-12-30 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_auto_20201230_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Polla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('me', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='voting',
            name='candidates',
        ),
        migrations.AddField(
            model_name='voting',
            name='polla',
            field=models.ManyToManyField(related_name='votings', to='voting.Polla'),
        ),
    ]
