# Generated by Django 2.0 on 2021-01-05 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_merge_20210105_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionorder',
            name='question',
        ),
        migrations.DeleteModel(
            name='QuestionOrder',
        ),
    ]
