# Generated by Django 2.0 on 2020-12-30 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0008_auto_20201230_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polla',
            name='me',
        ),
        migrations.RemoveField(
            model_name='polla',
            name='url',
        ),
        migrations.AddField(
            model_name='polla',
            name='age',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='polla',
            name='auto_community',
            field=models.TextField(choices=[('AN', 'Andalucia'), ('AR', 'Aragon'), ('AS', 'Asturias'), ('BA', 'Baleares'), ('CA', 'Canarias'), ('CT', 'Cantabria'), ('CAM', 'Castilla-Mancha'), ('CAL', 'Castilla-Leon'), ('CAT', 'Cataluña'), ('CE', 'Ceuta'), ('EX', 'Extremadura'), ('GA', 'Galicia'), ('LR', 'La-Rioja'), ('MA', 'Madrid'), ('ME', 'Melilla'), ('MU', 'Murcia'), ('NA', 'Navarra'), ('PV', 'País-Vasco'), ('VA', 'Valencia')], default='AN'),
        ),
        migrations.AddField(
            model_name='polla',
            name='sex',
            field=models.TextField(blank=True, choices=[('H', 'HOMBRE'), ('M', 'MUJER')], null=True),
        ),
        migrations.AlterField(
            model_name='polla',
            name='name',
            field=models.TextField(),
        ),
    ]
