# Generated by Django 2.0 on 2020-12-30 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0009_auto_20201230_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='political_party',
            field=models.TextField(choices=[('PP', 'Partido popular'), ('PSOE', 'Partido Socialista Obrero Español'), ('UP', 'Unidas Podemos'), ('PACMA', 'PACMA'), ('VOX', 'VOX'), ('CS', 'Ciudadanos')], default='PACMA'),
        ),
        migrations.AddField(
            model_name='polla',
            name='political_party',
            field=models.TextField(choices=[('PP', 'Partido popular'), ('PSOE', 'Partido Socialista Obrero Español'), ('UP', 'Unidas Podemos'), ('PACMA', 'PACMA'), ('VOX', 'VOX'), ('CS', 'Ciudadanos')], default='PACMA'),
        ),
    ]
