# Generated by Django 2.0 on 2021-01-05 16:31

from django.db import migrations, models
import voting.models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0010_auto_20210105_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, validators=[voting.models.validate_end_date]),
        ),
    ]
