# Generated by Django 2.0 on 2020-12-30 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0011_auto_20201230_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='candidates',
            field=models.ManyToManyField(null=True, related_name='votings', to='voting.Candidate'),
        ),
    ]
