# Generated by Django 2.0 on 2020-12-30 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0014_auto_20201230_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
