# Generated by Django 2.0 on 2021-01-02 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0015_candidate_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='sex',
            field=models.TextField(choices=[('H', 'HOMBRE'), ('M', 'MUJER')], default='H'),
        ),
    ]
