# Generated by Django 2.0 on 2021-01-02 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0016_auto_20210102_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='escanios',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
