# Generated by Django 2.0 on 2021-01-05 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_merge_20210104_2006'),
        ('voting', '0004_questionordering'),
        ('voting', '0004_auto_20201228_2045'),
        ('voting', '0011_auto_20210105_1631'),
        ('voting', '0017_voting_escanios'),
        ('voting', '0004_multiplevoting'),
        ('voting', '0004_readonlyvoting'),
        ('voting', '0006_auto_20210102_1312'),
    ]

    operations = [
    ]
