# Generated by Django 2.0 on 2021-02-09 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0017_voting_escanios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='escanios',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
