# Generated by Django 2.0 on 2021-01-05 19:22

from django.db import migrations, models
import voting.models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0018_merge_20210105_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, validators=[voting.models.validate_end_date]),
        ),
        migrations.AlterField(
            model_name='voting',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, validators=[voting.models.validate_start_date]),
        ),
    ]
