# Generated by Django 2.0 on 2021-01-06 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0019_auto_20210105_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='escanios',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
