# Generated by Django 2.0 on 2021-01-06 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_auto_20210105_1934'),
        ('voting', '0019_auto_20210105_1922'),
    ]

    operations = [
    ]
