# Generated by Django 2.0 on 2021-01-06 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0019_auto_20210105_1922'),
        ('voting', '0005_auto_20210106_1058'),
    ]

    operations = [
    ]
