# Generated by Django 2.0 on 2021-01-06 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0020_auto_20210106_0824'),
        ('voting', '0021_auto_20210106_1146'),
    ]

    operations = [
    ]
