# Generated by Django 2.0 on 2021-01-06 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0021_auto_20210106_0104'),
        ('voting', '0022_merge_20210106_1255'),
    ]

    operations = [
    ]
