# Generated by Django 2.0 on 2021-01-11 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0023_merge_20210106_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abreviatura', models.TextField(max_length=3)),
                ('nombre', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='candidate',
            name='auto_community',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate', to='voting.Community'),
        ),
    ]
