# Generated by Django 2.0 on 2021-01-14 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0023_merge_20210106_1720'),
        ('voting', '0007_auto_20210114_0641'),
    ]

    operations = [
    ]
