# Generated by Django 2.0 on 2021-01-14 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0024_merge_20210114_0807'),
        ('voting', '0025_auto_20210111_1805'),
    ]

    operations = [
    ]
