# Generated by Django 2.0 on 2021-01-12 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0026_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program', to='voting.Party'),
        ),
    ]
