# Generated by Django 2.0 on 2021-01-13 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0027_auto_20210112_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(blank=True, null=True)),
                ('plank', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='program',
            old_name='plank',
            new_name='overview',
        ),
        migrations.RemoveField(
            model_name='program',
            name='number',
        ),
        migrations.RemoveField(
            model_name='program',
            name='party',
        ),
        migrations.AddField(
            model_name='party',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='party', to='voting.Program'),
        ),
        migrations.AddField(
            model_name='program',
            name='title',
            field=models.CharField(default='default', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plank',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plank', to='voting.Program'),
        ),
    ]
