# Generated by Django 2.0 on 2021-01-14 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0026_merge_20210114_0816'),
        ('voting', '0028_auto_20210113_1545'),
    ]

    operations = [
    ]
