# Generated by Django 2.0 on 2021-01-16 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_auto_20210115_1541'),
        ('voting', '0030_auto_20210114_1818'),
    ]

    operations = [
    ]
