# Generated by Django 2.0 on 2021-01-16 11:41

from django.db import migrations, models
import voting.models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0031_merge_20210116_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, validators=[voting.models.validate_end_date]),
        ),
    ]
