# Generated by Django 2.0 on 2021-01-21 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0033_voting_lugar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voting',
            name='lugar',
        ),
    ]
